.Dd $Mdocdate: May 19 2024 $
.Dt MAN 1
.Os
.Sh NAME 
.Nm codex
.Nd generate random text
.Sh SYNOPSIS 
.Nm codex
.Op Fl hcp
.Op Fl t Ar number 
.Op Fl w Ar word
.Op Fl f Ar file
.Op Fl o Ar output

codex --help

cat file | codex -c > output

codex -c -f file -o output

cat input.csv | codex -t 1000 -w ciao --output file.out -p

.Sh DESCRIPTION

The
.Nm
utility
displays the
manual page entitled
.Ar name .
.\" Pages may be selected according to
.\" a specific category
.\" .Pq Ar section
.\" or
.\" machine architecture
.\" .Pq Ar subsection .
.\" .Pp
.\" The options are as follows:
.\" .Bl -tag -width Ds
.\" .It Fl a
.\" Display all matching manual pages.
.\" .It Fl C Ar file
.\" Use the specified
.\" .Ar file
.\" instead of the default configuration file.
.\" This permits users to configure their own manual environment.
.\" See
.\" .Xr man.conf 5
.\" for a description of the contents of this file.
.\" .It Fl c
.\" Copy the manual page to the standard output instead of using
.\" .Xr less 1
.\" to paginate it.
.\" This is done by default if the standard output is not a terminal device.
.\" .Pp
.\" When using
.\" .Fl c ,
.\" most terminal devices are unable to show the markup.
.\" To print the output of
.\" .Nm
.\" to the terminal with markup but without using a pager, pipe it to
.\" .Xr ul 1 .
.\" To remove the markup, pipe the output to
.\" .Xr col 1
.\" .Fl b
.\" instead.
.\" .It Fl f
.\" A synonym for
.\" .Xr whatis 1 .
.\" It searches for
.\" .Ar name
.\" in manual page names and displays the header lines from all matching pages.
.\" The search is case insensitive and matches whole words only.
.\" .It Fl h
.\" Display only the SYNOPSIS lines of the requested manual pages.
.\" Implies
.\" .Fl a
.\" and
.\" .Fl c .
.\" .It Fl k
.\" A synonym for
.\" .Xr apropos 1 .
.\" Instead of
.\" .Ar name ,
.\" an expression can be provided using the syntax described in the
.\" .Xr apropos 1
.\" manual.
.\" By default, it displays the header lines of all matching pages.
.\" .It Fl l
.\" A synonym for
.\" .Xr mandoc 1 .
.\" The
.\" .Ar name
.\" arguments are interpreted as filenames.
.\" No search is done and
.\" .Ar file ,
.\" .Ar path ,
.\" .Ar section ,
.\" .Ar subsection ,
.\" and
.\" .Fl w
.\" are ignored.
.\" This option implies
.\" .Fl a .
.\" .It Fl M Ar path
.\" Override the list of directories to search for manual pages.
.\" The supplied
.\" .Ar path
.\" must be a colon
.\" .Pq Ql \&:
.\" separated list of directories.
.\" This option also overrides the environment variable
.\" .Ev MANPATH
.\" and any directories specified in the
.\" .Xr man.conf 5
.\" file.
.\" .It Fl m Ar path
.\" Augment the list of directories to search for manual pages.
.\" The supplied
.\" .Ar path
.\" must be a colon
.\" .Pq Ql \&:
.\" separated list of directories.
.\" These directories will be searched before those specified using the
.\" .Fl M
.\" option, the
.\" .Ev MANPATH
.\" environment variable, the
.\" .Xr man.conf 5
.\" file, or the default directories.
.\" .It Fl S Ar subsection
.\" Only show pages for the specified
.\" .Xr machine 1
.\" architecture.
.\" .Ar subsection
.\" is case insensitive.
.\" .Pp
.\" By default manual pages for all architectures are installed.
.\" Therefore this option can be used to view pages for one
.\" architecture whilst using another.
.\" .Pp
.\" This option overrides the
.\" .Ev MACHINE
.\" environment variable.
.\" .Tg s
.\" .It Oo Fl s Oc Ar section
.\" Only select manuals from the specified
.\" .Ar section .
.\" The currently available sections are:
.\" .Pp
.\" .Bl -tag -width "localXXX" -offset indent -compact
.\" .It 1
.\" General commands
.\" .Pq tools and utilities .
.\" .It 2
.\" System calls and error numbers.
.\" .It 3
.\" Library functions.
.\" .It 3p
.\" .Xr perl 1
.\" programmer's reference guide.
.\" .It 4
.\" Device drivers.
.\" .It 5
.\" File formats.
.\" .It 6
.\" Games.
.\" .It 7
.\" Miscellaneous information.
.\" .It 8
.\" System maintenance and operation commands.
.\" .It 9
.\" Kernel internals.
.\" .El
.\" .It Fl w
.\" List the pathnames of all matching manual pages instead of displaying
.\" any of them.
.\" If no
.\" .Ar name
.\" is given, list the directories that would be searched.
.\" .El
.\" .Pp

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h, -help
Print usage information and exit.
.It Fl v, -version
Print version information and exit.
.It Fl c, -csv 
Read source text and map words data to a standard CSV format. If no 
.Ar file 
is specified takes the text from 
.Ar stdin .
.It Fl t, -text Ar number
Generate text with
.Ar number
words. If no
.Fl w
is specified, it starts randomly from '.', '?' or '!'. If no
.Fl f 
is specified, it reads the standard CSV from
.Ar stdin .
.It Fl w, -word Ar word
Specify starting 
.Ar word
for text generation.
.It Fl p, -parallel
Run command using parallel processeses.
.It Fl f, -file Ar file
Input
.Ar file
to convert to CSV or to start generation from.
.It Fl o, -output Ar file
Output  
.Ar file
where csv or generated text are written.
.Sh AUTHORS
Codex was written by Ionut Cicio.
